name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # ou '3.11', evite 3.13 que ainda não é suportado

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install

      - name: Run unit tests and generate coverage
        run: |
          poetry run coverage run -m unittest discover -s tests.unit
          poetry run coverage xml
        
      - name: Run Integration tests
        shell: bash
        if: runner.os != 'Windows'
        run: |
          poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload --env-file .env & \
          sleep 1 && \
          poetry run python -m unittest tests.integration && \
          pkill -f "uvicorn main:app"

      - name: Run Integration tests (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Start-Process -NoNewWindow -FilePath poetry -ArgumentList 'run','uvicorn','main:app','--host','0.0.0.0','--port','8000','--reload','--env-file','.env'
          Start-Sleep -Seconds 2
          poetry run python -m unittest tests.integration
          Get-Process -Name "python" | Where-Object { $_.Path -like "*uvicorn*" } | Stop-Process -Force

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: true

